name: Android Cloud Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Assemble Debug APK
    runs-on: ubuntu-latest

    env:
      JAVA_VERSION: "17"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
      - name: Install CMake 3.18.1
        run: sdkmanager "cmake;3.18.1"
      - name: Make Gradle executable
        run: chmod +x ./OpenPS/gradlew
      - name: Build with Gradle
        working-directory: ./OpenPS
        run: ./gradlew assembleDebug
      - name: List build output directory
        run: ls -R ./OpenPS/app/build/outputs/
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: ./OpenPS/app/build/outputs/apk/debug/app-debug.apk
